### ISSUE TITLE
Comments from Qin

### ISSUE THREAD

**Issue by boucadair** [boucadair/enhanced-acl-netmod#10]
> These comments can be summarized as follows:
> 1.	We need to clarify the relationship between draft-dbb and draft-ma-opsawg-ucl-acl
> 2.	Section 3.3 and Section 3.8 seems related, not sure whether these two section should be consolidated
> 3.	How match element grouping in pre-defined set is different from configuration template?
> Happy to discuss with you about these comments if needed.
>

**Comment by oscargdd** [comment]
Done in the draft
