### ISSUE TITLE
Payload match Clarification

### ISSUE THREAD

**Issue by sbarguil** [boucadair/enhanced-acl-netmod#15]
payload match is strange:

it should be?

a) value in hex 
b) mask in hex 
c) offset-type ip/l4/payload 
d) offset-value in B from the offset-type -> pbb difficult to agree on this as different vendors may support different length -> 

[here](https://datatracker.ietf.org/doc/draft-khare-idr-bgp-flowspec-payload-match/08/) is a draft dedicated to this here

**Comment by sbarguil** [comment]
To add more text to clarify and explain the usage of the Payload match in the text.

**Comment by boucadair** [comment]
Already fixed in 01
