### ISSUE TITLE
Comments from Victor

### ISSUE THREAD

**Issue by boucadair** [boucadair/enhanced-acl-netmod#19]
Hi Med

I put below some editorial and readability improvements for the draft. Unfortunately, I did them with the version prior to Feb 1st. 
 
Abstract:
 
I would replace "This document discusses a set of extensions that fix many of the limitations of the ACL model as initially defined in RFC 8519." By "This document discusses a set of extensions that address some of the limitations of the ACL model as defined in RFC 8519." because it might not completely fix all the limitations. 
 
1. Introduction
 
Access control lists (ACLs)  Access Control Lists (ACLs)
 
If it is needed, for example,  If, for example, it is needed 
 
entering IP address  entering the IP address 
 
3.1.  Suboptimal Configuration: Lack of Support for Lists of Prefixes
 
IP prefix related data nodes  IP prefix-related data nodes 
 
DDoS attacks (e.g., RFC9132] when a set of sources are involved  DDoS attacks, e.g., [RFC9132], when a set of sources are involved
 
This sentence is not clear for me: 
 
“Such a configuration is suboptimal for both: - Network controllers that need to manipulate large files.” I think it is missing some information. Network controllers and… My guess is that it should be something like 
 
Such a configuration is suboptimal for both: network controllers and devices. Network controllers need to manipulate large files and they will need to pass all or a subset of the configuration to the underlying network devices. The devices will need to maintain the information locally and perform multiple configurations.
 
Confirguration  configuration
 
(Figure 2 depicts  Figure 2 depicts
 
3.2.  Manageability: Impossibility to Use Aliases or Defined Sets
 
Introduing  introducing
 
Each category is modelled 
 
Make uses  make use
 
ICMP sets: Uses  ICMP Used
 
to managed resources   to manage resources 
 
3.4. Partial or Lack of IPv4/IPv6 Fragment Handling
 
The sentence "does not support fragment handling capability for IPv6" I would changed it to "does not support fragment handling for IPv6" to improve readability
 
IPv4 by means of 'flags'  IPv4 through the use of 'flags'
 
allow a bitmask to be defined  allow the use of bitmasks.
 
Defining a new IPv4/IPv6 matching field called 'fragment' is thus required  As a result, a new IPv4/IPv6 matching field called 'fragment' is defined 
 
3.5.  Suboptimal TCP Flags Handling
 
The sentence "Defining this field to be defined as a flag bitmask together with a set of operations is meant to efficiently handle TCP flags filtering rules" I would changed it to "Defining this field as a flag bitmask with a set of operations can improve the efficiency of handling TCP flags filtering rules" 
 
3.6.  Rate-Limit Action
 
Such capability is not currently supported  This capability (as it was already described)
 
3.7.  Payload-based Filtering
                                                                                               
Some transport protocols use existing protocols  Some transport protocols rely on existing protocols
 
It is not clear to me why this section highlights the same gap in the two models. Someone can ask for a solution. 
 
3.8.  Reuse the ACLs Content Across Several Devices
 
following the hierarchy of the network topology  based on the network topology hierarchy
 
“then, that same ACL can be used (or referenced to) in several devices (including termination points) within the same network” I would change it for “then reused or referenced across multiple devices, including termination points within the same network”
 
4.5.  Rate-Limit Traffic
 
(#example_5) shows an ACL example to rate-limit incoming SYNs during a SYN flood attack.  I think it is a missing link to the figure

YANG file some typos

          leaf-list protocol {
            type union {
              type uint8;
              type string; //Check if we can reuse an IANA-maintained module
            }
            description
              "Value of the protocl set.";  protocol
          }
 
Regards,
 
Victor

**Comment by oscargdd** [comment]
Done in the latest version of the draft

**Comment by vlopezalvarez** [comment]
thanks @oscargdd
