### ISSUE TITLE
Implement all the recos in draft-boucadair-netmod-iana-registries

### ISSUE THREAD

**Issue by boucadair** [boucadair/enhanced-acl-netmod#23]

**Comment by oscargdd** [comment]
can be closed as it is already in the introduction 

The document also defines an IANA-maintained module for ICMP types. The design of the module adheres with the recommendations in [[I-D.boucadair-netmod-iana-registries](https://boucadair.github.io/enhanced-acl-netmod/draft-ietf-netmod-acl-extensions.html#I-D.boucadair-netmod-iana-registries)]. A template to generate the module is available at [Appendix A](https://boucadair.github.io/enhanced-acl-netmod/draft-ietf-netmod-acl-extensions.html#template). Readers should refer to the IANA website [REF_TBC] to retrieve the latest version of the module. The module is provided in [Appendix B](https://boucadair.github.io/enhanced-acl-netmod/draft-ietf-netmod-acl-extensions.html#iana-icmp) for the users convenience, but that appendix will be removed from the final RFC.
