### ISSUE TITLE
Action Redirect

### ISSUE THREAD

**Issue by sbarguil** [boucadair/enhanced-acl-netmod#5]
Can we complement the actions with a redirect option.

This will be highly dependant of the routers capabilities but this redirection can be to a Captive Portal for HTTP traffic, for example:

```
            entry 30 create
                match protocol tcp
                    dst-ip 10.10.10.91/24
                    dst-port eq 80
                exit
                action http-redirect "http://100.0.0.2/login.cgi?mac=$MAC$sap=$S
AP&ip=$IP&orig_url=$URL"
```

**Comment by sbarguil** [comment]
Do we want to make it at IP or application Level. It requires further discussions: usage and possible implementations.

**Comment by boucadair** [comment]
@sbarguil, any update on this?

**Comment by boucadair** [comment]
As per the proposed plan in IETF#117
